version: '3.8'

services:
  redis:
    image: 'redis:alpine'
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - live

  rabbitmq:
    image: 'rabbitmq:latest'
    ports:
      - '5672:5672'
    networks:
      - live

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - .env.dev
    depends_on:
      - db
      - rabbitmq
      - redis
    networks:
      - live
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=myshop
    networks:
      - live

  celery_worker:
    build: .
    command: celery -A myshop worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - rabbitmq
    env_file:
      - .env.dev
    networks:
      - live

volumes:
  postgres_data:
  redis_data:

networks:
  live:
