# Generated by Django 3.0.14 on 2023-10-23 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
    ]
